/*
 * main_skeleton.c - reference main.c integration for tinychaos firmware.
 *
 * NOT a drop-in replacement for the CubeMX-generated main.c. This file
 * shows the integration pattern that the eventual real main.c should
 * follow. After running CubeMX on tinychaos.ioc, copy the relevant blocks
 * below into the matching CubeMX "USER CODE BEGIN/END" sections of the
 * generated Core/Src/main.c. Do NOT replace the whole file, or CubeMX will
 * stomp your edits on the next regeneration.
 *
 * The intent of this skeleton is to be readable as documentation: it shows
 * which modules are called, in what order, and from which callbacks.
 */

#include <stdint.h>

#include "main.h"              /* generated by CubeMX */
#include "entropy_config.h"
#include "entropy_protocol.h"

#if defined(ENTROPY_TRANSPORT_USB)
  #include "usb_stream.h"
  #define stream_init  usb_stream_init
  #define stream_send  usb_stream_send
  #define stream_pump  usb_stream_pump
#elif defined(ENTROPY_TRANSPORT_UART)
  #include "serial_stream.h"
  #define stream_init  serial_stream_init
  #define stream_send  serial_stream_send
  #define stream_pump  serial_stream_pump
#else
  #error "Define ENTROPY_TRANSPORT_USB or ENTROPY_TRANSPORT_UART in entropy_config.h"
#endif

/* These extern declarations are provided by the CubeMX-generated code. */
extern TIM_HandleTypeDef htim5;   /* free-running 1 MHz for time_us */

/* Sequence number for outgoing packets; rolls over at 2^32. */
static volatile uint32_t s_seq = 0;

/* Pre-built packet buffer. Sized for the maximum packet length. */
static uint8_t s_pkt[ENTROPY_PACKET_MAX_BYTES];

/* For step 5 (bring-up before ADC is wired in) we emit a counter pattern
 * instead of real ADC samples. Set this to 1 for the counter mode; set to
 * 0 once adc_capture.c is feeding samples via adc_capture_on_half/full.
 */
#ifndef ENTROPY_USE_COUNTER_PATTERN
#define ENTROPY_USE_COUNTER_PATTERN 1
#endif

#if ENTROPY_USE_COUNTER_PATTERN

/* Synthetic counter source. Builds a packet whose samples are a 12-bit
 * counter so the host can spot drops or corruption visually. Called from
 * a periodic timer (TIM6 or TIM7) at PACKET_SAMPLE_RATE. The exact rate
 * is not critical for this mode.
 */
static void emit_counter_packet(void)
{
    static uint16_t counter = 0;
    uint16_t samples[PACKET_SAMPLE_COUNT];
    for (size_t i = 0; i < PACKET_SAMPLE_COUNT; ++i) {
        samples[i] = counter++ & 0x0FFFU;
    }
    const uint32_t now_us = __HAL_TIM_GET_COUNTER(&htim5);
    size_t n = entropy_packet_encode(s_pkt, sizeof s_pkt,
                                     s_seq++, now_us,
                                     samples, PACKET_SAMPLE_COUNT);
    if (n > 0) {
        (void)stream_send(s_pkt, n);
    }
}

/* HAL timer period elapsed callback for the counter-packet timer. */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM6) {
        emit_counter_packet();
    }
}

#endif /* ENTROPY_USE_COUNTER_PATTERN */

/* ---- ADC capture integration (step 6) ----
 *
 * Once adc_capture.c is integrated, the callbacks below are called from
 * the DMA half/full transfer complete callbacks. They build packets from
 * real ADC samples instead of the counter pattern.
 *
 * Comment out emit_counter_packet wiring and uncomment these once ready.
 */
#if !ENTROPY_USE_COUNTER_PATTERN

void adc_capture_on_half(const uint16_t *samples, size_t n)
{
    /* The DMA half-buffer holds PACKET_SAMPLE_COUNT samples by construction
     * (ADC_DMA_BUFFER_SIZE = 2 * PACKET_SAMPLE_COUNT). One half-buffer
     * therefore maps to exactly one outgoing packet.
     */
    const uint32_t now_us = __HAL_TIM_GET_COUNTER(&htim5);
    size_t encoded = entropy_packet_encode(s_pkt, sizeof s_pkt,
                                           s_seq++, now_us,
                                           samples, n);
    if (encoded > 0) {
        (void)stream_send(s_pkt, encoded);
    }
}

void adc_capture_on_full(const uint16_t *samples, size_t n)
{
    adc_capture_on_half(samples, n);
}

#endif /* !ENTROPY_USE_COUNTER_PATTERN */

/* ---- main() integration sketch ----
 *
 * In the CubeMX-generated main.c, after the existing peripheral init calls
 * and before the while(1) loop, paste:
 *
 *     // USER CODE BEGIN 2
 *     stream_init();
 *     if (!entropy_protocol_self_test()) {
 *         Error_Handler();
 *     }
 *     HAL_TIM_Base_Start_IT(&htim5);            // free-running 1 MHz
 *     // For counter-pattern bring-up:
 *     HAL_TIM_Base_Start_IT(&htim6);            // packet emit period
 *     // For real ADC capture:
 *     // adc_capture_start();
 *     // USER CODE END 2
 *
 * In the while(1) body, paste:
 *
 *     // USER CODE BEGIN WHILE
 *     while (1) {
 *         stream_pump();
 *         HAL_GPIO_TogglePin(LD1_GPIO_Port, LD1_Pin);
 *         HAL_Delay(500);
 *     }
 *     // USER CODE END WHILE
 *
 * Finally, in usbd_cdc_if.c (USB CDC path), inside CDC_TransmitCplt_FS:
 *
 *     extern void usb_stream_on_tx_complete(void);
 *     usb_stream_on_tx_complete();
 *
 * And in the UART completion callback (HAL_UART_TxCpltCallback, often in
 * stm32h7xx_it.c or main.c), call:
 *
 *     extern void serial_stream_on_tx_complete(void);
 *     if (huart->Instance == USART3) serial_stream_on_tx_complete();
 */
